
let sonar_results = {
    "total_count": 18207,
    "incomplete_results": false,
    "items": [
        {
        "id": 1222504,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMjIyNTA0",
        "name": "sonarqube",
        "full_name": "SonarSource/sonarqube",
        "private": false,
        "owner": {
            "login": "SonarSource",
            "id": 545988,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjU0NTk4OA==",
            "avatar_url": "https://avatars.githubusercontent.com/u/545988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SonarSource",
            "html_url": "https://github.com/SonarSource",
            "followers_url": "https://api.github.com/users/SonarSource/followers",
            "following_url": "https://api.github.com/users/SonarSource/following{/other_user}",
            "gists_url": "https://api.github.com/users/SonarSource/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SonarSource/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SonarSource/subscriptions",
            "organizations_url": "https://api.github.com/users/SonarSource/orgs",
            "repos_url": "https://api.github.com/users/SonarSource/repos",
            "events_url": "https://api.github.com/users/SonarSource/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SonarSource/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "html_url": "https://github.com/SonarSource/sonarqube",
        "description": "Continuous Inspection",
        "fork": false,
        "url": "https://api.github.com/repos/SonarSource/sonarqube",
        "forks_url": "https://api.github.com/repos/SonarSource/sonarqube/forks",
        "keys_url": "https://api.github.com/repos/SonarSource/sonarqube/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SonarSource/sonarqube/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SonarSource/sonarqube/teams",
        "hooks_url": "https://api.github.com/repos/SonarSource/sonarqube/hooks",
        "issue_events_url": "https://api.github.com/repos/SonarSource/sonarqube/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SonarSource/sonarqube/events",
        "assignees_url": "https://api.github.com/repos/SonarSource/sonarqube/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SonarSource/sonarqube/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SonarSource/sonarqube/tags",
        "blobs_url": "https://api.github.com/repos/SonarSource/sonarqube/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SonarSource/sonarqube/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SonarSource/sonarqube/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SonarSource/sonarqube/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SonarSource/sonarqube/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SonarSource/sonarqube/languages",
        "stargazers_url": "https://api.github.com/repos/SonarSource/sonarqube/stargazers",
        "contributors_url": "https://api.github.com/repos/SonarSource/sonarqube/contributors",
        "subscribers_url": "https://api.github.com/repos/SonarSource/sonarqube/subscribers",
        "subscription_url": "https://api.github.com/repos/SonarSource/sonarqube/subscription",
        "commits_url": "https://api.github.com/repos/SonarSource/sonarqube/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SonarSource/sonarqube/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SonarSource/sonarqube/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SonarSource/sonarqube/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SonarSource/sonarqube/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SonarSource/sonarqube/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SonarSource/sonarqube/merges",
        "archive_url": "https://api.github.com/repos/SonarSource/sonarqube/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SonarSource/sonarqube/downloads",
        "issues_url": "https://api.github.com/repos/SonarSource/sonarqube/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SonarSource/sonarqube/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SonarSource/sonarqube/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SonarSource/sonarqube/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SonarSource/sonarqube/labels{/name}",
        "releases_url": "https://api.github.com/repos/SonarSource/sonarqube/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SonarSource/sonarqube/deployments",
        "created_at": "2011-01-05T11:05:17Z",
        "updated_at": "2022-09-19T03:28:44Z",
        "pushed_at": "2022-09-16T20:03:30Z",
        "git_url": "git://github.com/SonarSource/sonarqube.git",
        "ssh_url": "git@github.com:SonarSource/sonarqube.git",
        "clone_url": "https://github.com/SonarSource/sonarqube.git",
        "svn_url": "https://github.com/SonarSource/sonarqube",
        "homepage": "http://www.sonarqube.org",
        "size": 885170,
        "stargazers_count": 7158,
        "watchers_count": 7158,
        "language": "Java",
        "has_issues": false,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "forks_count": 1728,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 3,
        "license": {
            "key": "lgpl-3.0",
            "name": "GNU Lesser General Public License v3.0",
            "spdx_id": "LGPL-3.0",
            "url": "https://api.github.com/licenses/lgpl-3.0",
            "node_id": "MDc6TGljZW5zZTEy"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "code-quality",
            "sonarqube",
            "static-analysis"
        ],
        "visibility": "public",
        "forks": 1728,
        "open_issues": 3,
        "watchers": 7158,
        "default_branch": "master",
        "score": 1.0
        },
        {
        "id": 2465723,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNDY1NzIz",
        "name": "Sonarr",
        "full_name": "Sonarr/Sonarr",
        "private": false,
        "owner": {
            "login": "Sonarr",
            "id": 1082903,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEwODI5MDM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1082903?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Sonarr",
            "html_url": "https://github.com/Sonarr",
            "followers_url": "https://api.github.com/users/Sonarr/followers",
            "following_url": "https://api.github.com/users/Sonarr/following{/other_user}",
            "gists_url": "https://api.github.com/users/Sonarr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Sonarr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Sonarr/subscriptions",
            "organizations_url": "https://api.github.com/users/Sonarr/orgs",
            "repos_url": "https://api.github.com/users/Sonarr/repos",
            "events_url": "https://api.github.com/users/Sonarr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Sonarr/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "html_url": "https://github.com/Sonarr/Sonarr",
        "description": "Smart PVR for newsgroup and bittorrent users.",
        "fork": false,
        "url": "https://api.github.com/repos/Sonarr/Sonarr",
        "forks_url": "https://api.github.com/repos/Sonarr/Sonarr/forks",
        "keys_url": "https://api.github.com/repos/Sonarr/Sonarr/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Sonarr/Sonarr/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Sonarr/Sonarr/teams",
        "hooks_url": "https://api.github.com/repos/Sonarr/Sonarr/hooks",
        "issue_events_url": "https://api.github.com/repos/Sonarr/Sonarr/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Sonarr/Sonarr/events",
        "assignees_url": "https://api.github.com/repos/Sonarr/Sonarr/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Sonarr/Sonarr/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Sonarr/Sonarr/tags",
        "blobs_url": "https://api.github.com/repos/Sonarr/Sonarr/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Sonarr/Sonarr/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Sonarr/Sonarr/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Sonarr/Sonarr/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Sonarr/Sonarr/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Sonarr/Sonarr/languages",
        "stargazers_url": "https://api.github.com/repos/Sonarr/Sonarr/stargazers",
        "contributors_url": "https://api.github.com/repos/Sonarr/Sonarr/contributors",
        "subscribers_url": "https://api.github.com/repos/Sonarr/Sonarr/subscribers",
        "subscription_url": "https://api.github.com/repos/Sonarr/Sonarr/subscription",
        "commits_url": "https://api.github.com/repos/Sonarr/Sonarr/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Sonarr/Sonarr/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Sonarr/Sonarr/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Sonarr/Sonarr/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Sonarr/Sonarr/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Sonarr/Sonarr/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Sonarr/Sonarr/merges",
        "archive_url": "https://api.github.com/repos/Sonarr/Sonarr/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Sonarr/Sonarr/downloads",
        "issues_url": "https://api.github.com/repos/Sonarr/Sonarr/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Sonarr/Sonarr/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Sonarr/Sonarr/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Sonarr/Sonarr/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Sonarr/Sonarr/labels{/name}",
        "releases_url": "https://api.github.com/repos/Sonarr/Sonarr/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Sonarr/Sonarr/deployments",
        "created_at": "2011-09-27T05:57:16Z",
        "updated_at": "2022-09-19T02:46:06Z",
        "pushed_at": "2022-09-18T15:01:06Z",
        "git_url": "git://github.com/Sonarr/Sonarr.git",
        "ssh_url": "git@github.com:Sonarr/Sonarr.git",
        "clone_url": "https://github.com/Sonarr/Sonarr.git",
        "svn_url": "https://github.com/Sonarr/Sonarr",
        "homepage": "https://sonarr.tv",
        "size": 291712,
        "stargazers_count": 7717,
        "watchers_count": 7717,
        "language": "C#",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 1064,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 170,
        "license": {
            "key": "gpl-3.0",
            "name": "GNU General Public License v3.0",
            "spdx_id": "GPL-3.0",
            "url": "https://api.github.com/licenses/gpl-3.0",
            "node_id": "MDc6TGljZW5zZTk="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            
        ],
        "visibility": "public",
        "forks": 1064,
        "open_issues": 170,
        "watchers": 7717,
        "default_branch": "develop",
        "score": 1.0
        }
    ]
}

export default sonar_results;